package com.dkit.GD2.KeithJoyce;

public enum EditStudentMenu
{
    QUIT_STUDENT_EDIT_MENU,
    EDIT_STUDENT_NAME,
    EDIT_STUDENT_EMAIL,
    EDIT_STUDENT_ID,
    EDIT_STUDENT_PHONE_NUMBER,
    EDIT_STUDENT_COMPUTER_ON_LOAN;
}
